#!/usr/bin/env python3
"""Create a private DSMC source overlay for building DSMC with IAC commands."""

import argparse
import os
from pathlib import Path
import shutil
from typing import List


BRIDGE_FILES = {
    "iac.cpp",
    "iac.h",
    "iacbridge.cpp",
    "iacbridge.h",
    "iacgrid.cpp",
    "iacgrid.h",
    "isthmus.cpp",
    "isthmus.h",
    "source.cpp",
    "source.h",
    "surface.cpp",
    "surface.h",
    "voxel.cpp",
    "voxel.h",
}


SKIP_PREFIXES = ("Obj_", "Obj_shared_")
SKIP_NAMES = {
    "Makefile.package",
    "Makefile.package.settings",
    "style_command.h",
    "style_command.tmp",
    "style_collide.h",
    "style_collide.tmp",
    "style_compute.h",
    "style_compute.tmp",
    "style_dump.h",
    "style_dump.tmp",
    "style_fix.h",
    "style_fix.tmp",
    "style_react.h",
    "style_react.tmp",
    "style_region.h",
    "style_region.tmp",
    "style_surf_collide.h",
    "style_surf_collide.tmp",
    "style_surf_react.h",
    "style_surf_react.tmp",
}


def symlink_or_copy(source: Path, dest: Path) -> None:
    if dest.exists() or dest.is_symlink():
        if dest.is_dir() and not dest.is_symlink():
            shutil.rmtree(dest)
        else:
            dest.unlink()
    try:
        os.symlink(source, dest, target_is_directory=source.is_dir())
    except OSError:
        if source.is_dir():
            shutil.copytree(source, dest)
        else:
            shutil.copy2(source, dest)


def copy_directory(source: Path, dest: Path) -> None:
    if dest.exists() or dest.is_symlink():
        if dest.is_dir() and not dest.is_symlink():
            shutil.rmtree(dest)
        else:
            dest.unlink()
    shutil.copytree(source, dest)


def clear_directory(path: Path) -> None:
    if not path.exists():
        path.mkdir(parents=True)
        return
    if not path.is_dir():
        raise SystemExit(f"Overlay path exists but is not a directory: {path}")
    for item in path.iterdir():
        if item.is_dir() and not item.is_symlink():
            shutil.rmtree(item)
        else:
            item.unlink()


def patch_machine_makefiles(overlay_src: Path, include_flags: List[str], libs: List[str]) -> None:
    make_dir = overlay_src / "MAKE"
    if not make_dir.is_dir():
        return
    include_text = " ".join(include_flags)
    lib_text = " ".join(libs)
    for path in make_dir.glob("Makefile.*"):
        lines = path.read_text().splitlines()
        patched = []
        for line in lines:
            stripped = line.lstrip()
            if stripped.startswith("CCFLAGS") and "=" in line and include_text:
                patched.append(f"{line} {include_text}")
            elif stripped.startswith("LIB") and "=" in line and lib_text:
                patched.append(f"{line} {lib_text}")
            else:
                patched.append(line)
        path.write_text("\n".join(patched) + "\n")


def write_package(
    overlay_src: Path,
    iac_include: Path,
    iac_lib: Path,
    isthmus_includes: List[Path],
    isthmus_lib: Path,
) -> None:
    include_flags = (
        ["-std=c++17", f"-I{iac_include}"]
        + [f"-I{path}" for path in isthmus_includes]
    )
    libs = [str(iac_lib), str(isthmus_lib)]
    package = "\n".join(
        [
            "# Settings generated by isthmus-ablation-core for the DSMC overlay build",
            "# Do not edit; rerun the IAC CMake dsmc target instead.",
            "",
            f"PKG_INC =   {' '.join(include_flags)}",
            "PKG_PATH =  ",
            f"PKG_LIB =   {' '.join(libs)}",
            "PKG_CPP_DEPENDS = ",
            "PKG_LINK_DEPENDS = ",
            "",
            "PKG_SYSINC =  ",
            "PKG_SYSLIB =  ",
            "PKG_SYSPATH = ",
            "",
        ]
    )
    settings = "\n".join(
        [
            "# Settings generated by isthmus-ablation-core for the DSMC overlay build",
            "# Do not edit; rerun the IAC CMake dsmc target instead.",
            "",
        ]
    )
    (overlay_src / "Makefile.package").write_text(package)
    (overlay_src / "Makefile.package.settings").write_text(settings)


def should_skip(name: str) -> bool:
    return name in SKIP_NAMES or name in BRIDGE_FILES or name.startswith(SKIP_PREFIXES) or name.startswith("spa_")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dsmc-root", required=True, type=Path)
    parser.add_argument("--bridge-dir", required=True, type=Path)
    parser.add_argument("--overlay-src", required=True, type=Path)
    parser.add_argument("--iac-include", required=True, type=Path)
    parser.add_argument("--iac-lib", required=True, type=Path)
    parser.add_argument("--isthmus-include", action="append", default=[], type=Path)
    parser.add_argument("--isthmus-lib", required=True, type=Path)
    args = parser.parse_args()

    dsmc_src = args.dsmc_root / "src"
    if not dsmc_src.is_dir():
        raise SystemExit(f"DSMC root does not contain src/: {args.dsmc_root}")
    if not (dsmc_src / "Makefile").is_file():
        raise SystemExit(f"DSMC src directory does not contain Makefile: {dsmc_src}")
    if not args.bridge_dir.is_dir():
        raise SystemExit(f"IAC bridge directory does not exist: {args.bridge_dir}")
    if not args.iac_lib.is_file():
        raise SystemExit(f"IAC library does not exist yet: {args.iac_lib}")
    if not args.isthmus_lib.is_file():
        raise SystemExit(f"ISTHMUS library does not exist: {args.isthmus_lib}")

    clear_directory(args.overlay_src)

    include_flags = (
        ["-std=c++17", f"-I{args.iac_include.resolve()}"]
        + [f"-I{path.resolve()}" for path in args.isthmus_include]
    )
    libs = [str(args.iac_lib.resolve()), str(args.isthmus_lib.resolve())]

    for item in dsmc_src.iterdir():
        if should_skip(item.name):
            continue
        if item.name == "MAKE" and item.is_dir():
            copy_directory(item.resolve(), args.overlay_src / item.name)
        else:
            symlink_or_copy(item.resolve(), args.overlay_src / item.name)

    for name in sorted(BRIDGE_FILES):
        source = args.bridge_dir / name
        if not source.is_file():
            raise SystemExit(f"Missing bridge file: {source}")
        symlink_or_copy(source.resolve(), args.overlay_src / name)

    public_include = args.iac_include / "isthmus_ablation"
    if not public_include.is_dir():
        raise SystemExit(f"IAC public include directory does not exist: {public_include}")
    symlink_or_copy(public_include.resolve(), args.overlay_src / "isthmus_ablation")

    write_package(
        args.overlay_src,
        args.iac_include.resolve(),
        args.iac_lib.resolve(),
        [path.resolve() for path in args.isthmus_include],
        args.isthmus_lib.resolve(),
    )
    patch_machine_makefiles(args.overlay_src, include_flags, libs)

    readme = "\n".join(
        [
            "# DSMC/IAC Overlay",
            "",
            "This directory is generated by isthmus-ablation-core.",
            "It symlinks a clean DSMC source tree and the IAC bridge commands into a private build area.",
            "Delete the parent build directory to remove it.",
            "",
        ]
    )
    (args.overlay_src.parent / "README.md").write_text(readme)
    print(f"Wrote DSMC/IAC overlay: {args.overlay_src}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
